include:
  - project: 'shared/gitlab-ci-includes'
    ref: main
    file:
      - '/base.yml'
      - '/pypi-packages.yml'
      - '/debian-packages.yml'
      - '/python.yml'

variables:
  APTLY_BASE_REPOSITORY: common

stages:
  - test
  - build
  - publish

unit test and feature test:
  stage: test
  image: python:3.11
  script:
    - !reference [.add repositories, script]
    # TODO: Remove `apt-get` after !41
    - apt-get -y install python3-cyberfusion-common python3-cyberfusion-rabbitmq-consumer
    - pip install --no-cache-dir -r requirements/test.txt
    - pip install .
    - pip install --no-cache-dir -r usr/share/rabbitmq-consumer-documentation-server/debian_postinst.txt
    # TODO: Remove PYTHONPATH after !41
    - PYTHONPATH=$PYTHONPATH:/usr/lib/python3/dist-packages pytest -n 10 -vvv --cov-branch --cov=cyberfusion.RabbitMQConsumerDocumentationServer --cov-config=.coveragerc --cov-fail-under=95 --junitxml=report-pytest.xml
  artifacts:
    reports:
      junit: report-*.xml
